Repository ggacaferi/software-development, pull requests merged in 2025-06, with the labels that each got.

#64 Main to develop
  .editorconfig
  package.json
Labels: documentation

#67 feature: add github actions
  .github/workflows/Coverage.yml
  .github/workflows/Deployment.yml
  .github/workflows/Lint.yml
  jest.js
  package-lock.json
  package.json
Labels: enhancement

#69 docs: update README with deployment and testing info
  README.md
Labels: documentation

#71 Release/v1.2.0
  .github/dependabot.yml
  .github/workflows/Coverage.yml
  .github/workflows/Deployment.yml
  .github/workflows/Lint.yml
  .github/workflows/Test.yml
  README.md
  __tests__/snake-logic.test.js
  jest.js
  package-lock.json
  package.json
  src/boardPrinter.js
  src/floodFill.js
  src/headToHeadMovement.js
  src/index.js
  src/server.js
  src/snakeLogic.js
Labels: Release

#72 hotfix: update Railway CLI installation and dependencies
  .github/workflows/Deployment.yml
  package-lock.json
  package.json
Labels: bug

#86 feat: add evaluation, move selection functions for Battlesnake strategy and added tests
  __tests__/snake-logic.test.js
  src/snakeLogic.js
Labels: enhancement

#92 fixed package-lock eslint conflicts
  package-lock.json
Labels: bug

#93 Refactor/codebase
  src/boardPrinter.js
  src/floodFill.js
  src/headToHeadMovement.js
  src/index.js
  src/pathfinding.js
  src/server.js
  src/snakeLogic.js
Labels: enhancement

#95 Release/major v.2.0.0
  __tests__/snake-logic.test.js
  package-lock.json
  package.json
  src/boardPrinter.js
  src/floodFill.js
  src/headToHeadMovement.js
  src/index.js
  src/pathfinding.js
  src/server.js
  src/snakeLogic.js
Labels: Release

#98 hotfix: specify project ID in Railway deployment command
  .github/workflows/Deployment.yml
  docs/boardPrinter.js.html
  docs/floodFill.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/headToHeadMovement.js.html
  docs/index.html
  docs/index.js.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/server.js.html
  docs/snakeLogic.js.html
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
Labels: bug

#99 Revert "hotfix: specify project ID in Railway deployment command"
  .github/workflows/Deployment.yml
  docs/boardPrinter.js.html
  docs/floodFill.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/headToHeadMovement.js.html
  docs/index.html
  docs/index.js.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/server.js.html
  docs/snakeLogic.js.html
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
Labels: bug

#102 Feature/adding jsdocs
  .github/workflows/Deployment.yml
  docs/boardPrinter.js.html
  docs/floodFill.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/headToHeadMovement.js.html
  docs/index.html
  docs/index.js.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/server.js.html
  docs/snakeLogic.js.html
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
Labels: documentation, enhancement
